name: Deploy to AWS EC2

on:
  push:
    branches:
      - refactor/#81-CI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.1.1'

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Spring Boot Build
        run: ./gradlew clean build --exclude-task test

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/publicclassdev:latest .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/publicclassdev:latest

      - name: Create .env file
        run: |
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" > .env
          echo "EC2_WEB_PASSWORD=${{ secrets.EC2_WEB_PASSWORD }}" >> .env
          echo "EC2_PRIVATE_KEY=${{ secrets.EC2_PRIVATE_KEY }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
          echo "EC2_WEB_USERNAME=${{ secrets.EC2_WEB_USERNAME }}" >> .env
          echo "DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "github_token=${{ secrets.github_token }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "EC2_WEB_HOST=${{ secrets.EC2_WEB_HOST }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_SG_ID=${{ secrets.AWS_SG_ID }}" >> .env
          echo "EC2_WEB_SSH_PORT=${{ secrets.EC2_WEB_SSH_PORT }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

      - name: Debug .env file
        run: cat .env || echo ".env file does not exist"

      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_WEB_HOST }}
          username: ${{ secrets.EC2_WEB_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_WEB_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker stop publicclassdev
            sudo docker rm publicclassdev
            
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/publicclassdev:latest
            sudo docker run -it -d -p 8080:8080 --name publicclassdev --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/publicclassdev:latest
